Lesson5and6
nikitabranovitski/AN11_Android_NikitaBranovitski pull request #1
Opened 2021-11-02 15:17 UTC by nikitabranovitski

2021-11-06 08:45 UTC, MaximPilipeiko requested changes
Поправь пожалуйста задачи 2 и 3 в занятии 6.
Если не понятно, можем в понедельник после или перед занятием обсудить.

2021-11-06 08:45 UTC, MaximPilipeiko commented on Lesson_5/Task_2/Person.java
> +public class Person  implements Jacket, Pants, Shoes{
Person не является элементов одежды он не должен реализовывать интерфейсы Jacket, Pants, Shoes.
Он должен их агрегировать, т.е. содержать поля этих типов.

2021-11-06 08:45 UTC, MaximPilipeiko commented on Lesson_5/Task_3/Spaceport.java
> +public class Spaceport implements IStart {
Spaceport не должен реализовывать интерфейс IStart

2021-11-09 20:00 UTC, MaximPilipeiko requested changes

2021-11-09 20:00 UTC, MaximPilipeiko commented on Lesson_5/Task_2/Jacket.java
> +interface Jacket {
Не понимаю зачем два интерфейса?

2021-11-09 20:00 UTC, MaximPilipeiko commented on Lesson_5/Task_2/Jacket.java
> +interface Jacket {
Глянь плиз https://github.com/Y-Pazniak/AN11_Android/tree/main/Home_5/Task_5_3/src

2021-11-09 20:00 UTC, MaximPilipeiko commented on Lesson_5/Task_2/Jacket.java
> +interface Jacket {
Подойди пожалуйста на перерыве обсудим задание.

2021-11-09 20:00 UTC, MaximPilipeiko commented on Lesson_5/Task_3/Shuttle.java
> +public class Shuttle {
тоже что-то непонятное, два класса ```Shuttle```

2021-11-09 21:33 UTC, nikitabranovitski commented on Lesson_5/Task_2/Jacket.java
> +interface Jacket {
это я как то закоммитил неправильно
всё исправлю

2021-11-11 16:25 UTC, merged